### ISSUE TITLE
Invalid name of newsqa json

### ISSUE THREAD

**Issue by raj34521** [GauthierDmn/question_generation#3]
Hi..,
     I tried running code make_dataset.py. But in the links provided of newsqa dataser i didn't find newsqa json file. All i found was .questions file. Can you please provide me the link to get the json file which will be stored as "combined-newsqa-data-v1.json".

**Comment by HarbingerOfHell** [comment]
I had the same problem but if you run python maluuba/newsqa/data_generator.py as in the maluuba code, you get the combined file.

**Comment by raj34521** [comment]
Thanks

**Comment by DivyaWadehra** [comment]
can you send this file to wadehra83@gmail.com

Thanks & Regards
