### ISSUE TITLE
ValueError: Expected input batch_size (1216) to match target batch_size (1280)

### ISSUE THREAD

**Issue by raj34521** [GauthierDmn/question_generation#4]
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    loss = criterion(pred.view(-1, pred.size(2)), question.view(-1))
  File "/var/www/html/question_generate/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/var/www/html/question_generate/env/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 209, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/var/www/html/question_generate/env/lib/python3.6/site-packages/torch/nn/functional.py", line 1869, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1216) to match target batch_size (1280)

**Comment by raj34521** [comment]
I followed the same proedure as that given in README.md file

**Comment by sayduke** [comment]
I had same issues. I am checking shapes of args in criterion function but not sure I can correct this issue. 
If you found a solution for this, leave what you did.  
Thanks in advance..

**Comment by sayduke** [comment]
I solved this issue with reusing codes which used in training code. But after then, I found some errors during process.  that was easy to fix.

**Comment by oskrocha** [comment]
Can you please share your solution?

**Comment by mady143** [comment]
Hi @raj34521  @sayduke @oskrocha @GauthierDmn ,
Did any one resolved the issue regarding 
**ValueError: Expected input batch_size (1216) to match target batch_size (1280).**
I am getting the same issue i was unable to find the solution
can any one help me ...

Thanks and Regards,
Manikantha Sekhar.

Happy Coding...

**Comment by GauthierDmn** [comment]
Hi @mady143, I was pretty busy lately to give it a look but now I may be able to find time to fix this in the coming days. If you work on it before then, don't hesitate to submit a pull request.

**Comment by mady143** [comment]
Hi @GauthierDmn 
sure.. if i find the solution i will update it .
Thank you

**Comment by Githubhappy** [comment]
I solved this issue by changing 
1. loss = criterion(pred.view(-1, pred.size(2)), question[:, 1:].contiguous().view(-1))  in train.py
2. report_metrics function : if self.train to if self.training in utils.py
3. min(mc.list_valid_loss[-1], best_valid_loss)
I am able to train without error.

**Comment by mady143** [comment]
Hi 

> I solved this issue by changing
> 
> 1. loss = criterion(pred.view(-1, pred.size(2)), question[:, 1:].contiguous().view(-1))  in train.py
> 2. report_metrics function : if self.train to if self.training in utils.py
> 3. min(mc.list_valid_loss[-1], best_valid_loss)
>    I am able to train without error.

I modified the code as per your above lines but i was unable to resolve the error getting the same error 
**ValueError: Expected input batch_size (1216) to match target batch_size (1280).**

**Comment by mady143** [comment]
> I solved this issue by changing
> 
> 1. loss = criterion(pred.view(-1, pred.size(2)), question[:, 1:].contiguous().view(-1))  in train.py
> 2. report_metrics function : if self.train to if self.training in utils.py
> 3. min(mc.list_valid_loss[-1], best_valid_loss)
>    I am able to train without error.

When I was Changed to as per your code i am getting an another error stating that

here itself getting an error **writer.add_scalars("valid", {"loss": mc.list_valid_loss[-1],
                                     "accuracy": mc.list_valid_accuracy[-1],
                                     "perplexity": mc.list_valid_perplexity[-1],
                                     "epoch": mc.epoch})**

**IndexError: list index out of range**

**Comment by krishnats98** [comment]
> Hi @mady143, I was pretty busy lately to give it a look but now I may be able to find time to fix this in the coming days. If you work on it before then, don't hesitate to submit a pull request.

I am also having the same error.
Requesting you fix the error asap.
