### ISSUE TITLE
newsqa

### ISSUE THREAD

**Issue by DivyaWadehra** [GauthierDmn/question_generation#7]
can I get newsqa dataset processed one..

**Comment by mady143** [comment]
Hi @DivyaWadehra ,
follow bellow link and download the newqa dataset  but from bellow you can find csv file convert it into json file through online converter 
**https://www.microsoft.com/en-us/download/details.aspx?id=57162**

Thanks and Regards,
Manikantha Sekhar.
Happy Codding...

**Comment by mady143** [comment]
Hi @DivyaWadehra ,
else you can go through this repo and clone this repo seperately in your local  **https://github.com/Maluuba/newsqa** 

you have to download some datasets like stories from the bellow link 
**https://cs.nyu.edu/~kcho/DMQA/** and as well as

 download these data sets 
**http://nlp.stanford.edu/software/stanford-postagger-full-2015-04-20.zip**
**http://www.java2s.com/Code/Jar/s/Downloadslf4japi159rc1sourcesjar.htm**

and execute these comand
**python maluuba/newsqa/data_generator.py**  

now you can find the **combined-newsqa-data-v1.json** file  copy that file into your current project and run the bellow comands given in the README.md

Thanks and Regards,
Manikantha Sekhar,

Happy Codding...
